---

- stat:
    path: "{{ rai_node_data_dir }}/db.7z"
  register: db_tar

- name: Get raiblocks db snapshot
  command: /usr/local/bin/google_drive.py {{ raiblocks_db_file_id }} {{ rai_node_data_dir }}/db.7z
  when: db_tar.stat.md5 is not defined or db_tar.stat.md5 != raiblocks_db_md5

- name: Decompress db
  command: chdir={{ rai_node_data_dir }} /usr/bin/7za x db.7z -y


